language: android
notifications:
  email: false
android:
  components:
    - tools
    - build-tools-25.0.3
    - platform-tools
    - extra-android-m2repository
    - extra-google-android-support
    - android-23
    
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
deploy:
   file: app/build/outputs/apk/TeamCode-debug.apk
after_success:
    "curl --ftp-create-dirs -T app/build/outputs/apk/TeamCode-debug.apk -u $FTP_USER:$FTP_PASSWORD ftp://vhundef.net/public_html/$TRAVIS_BRANCH_TeamCode-debug.apk"
