version: 2
jobs:
  "Setup":
    working_directory: ~/code
    docker:
      - image: circleci/android:api-23-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - run:
          name: Switch timezone to Moscow
          command: sudo cp /usr/share/zoneinfo/Europe/Moscow /etc/localtime
      - checkout:
          post:  
             - cp -r licenses/. $ANDROID_HOME/licenses
  "DepInstall":       
    - run:
       name: Download Dependencies
       command: ./gradlew androidDependencies
  "Build":
    - run:
       name: Build assembleDebug
       command: ./gradlew assembleDebug
    - store_artifacts:
       path: TeamCode/build/outputs/apk
       destination: apk
  "Deploy":
    - run:
       name: Deploy
       command: sh ./deploy.sh $ftplogin $ftppass $CIRCLE_BRANCH $CIRCLE_COMPARE_URL $CIRCLE_BUILD_NUM
          
workflows:
  version: 2
  build:
    jobs:
      - "Setup"
      - "DepInstall"
        requires:
            - "Setup"
      - "Build"
        requires:
            - "DepInstall"
      - "Deploy"
        requires:
            - "Build"
