version: 2
jobs:
  build:
    docker:
      - image: bitriseio/docker-android
    working_directory: ~/code
    steps:
      - checkout
      - run:
          name: Build assembleDebug
          command: ./gradlew assembleDebug
      - store_artifacts:
          path: TeamCode/build/outputs/apk
          destination: apk
      - run:
          name: Deploy
          command: sh ./deploy.sh
