version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-23-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - run:
          name: Switch timezone to Moscow
          command: sudo cp /usr/share/zoneinfo/Europe/Moscow /etc/localtime
      - checkout:
          post:  
             - cp -r licenses/. $ANDROID_HOME/licenses
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Build assembleDebug
          command: ./gradlew assembleDebug
      - store_artifacts:
          path: TeamCode/build/outputs/apk
          destination: apk
      - run:
          name: Deploy
          command: sh ./deploy.sh $ftplogin $ftppass $CIRCLE_BRANCH $CIRCLE_COMPARE_URL $CIRCLE_BUILD_NUM
          
