version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-23-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    dependencies:
      pre:
    # Android SDK Platform 25
        - if [ ! -d "/usr/local/android-sdk-linux/platforms/android-25" ]; then echo y | android update sdk --no-ui --all --filter "android-25"; fi
    # Android SDK Build-tools, revision 25.0.0
        - if [ ! -d "/usr/local/android-sdk-linux/build-tools/25.0.5" ]; then echo y | android update sdk --no-ui --all --filter "build-tools-25.0.5"; fi
    # Android Support Repository, revision 39 / Local Maven repository for Support Libraries
        - if [ ! -d "/usr/local/android-sdk-linux/extras/android/m2repository/com/android/support/design/25.0.0" ]; then echo y | android update sdk --no-ui --all --filter "extra-android-m2repository"; fi
    

  cache_directories:
    - /usr/local/android-sdk-linux/platforms/android-25
    - /usr/local/android-sdk-linux/build-tools/25.0.0
    - /usr/local/android-sdk-linux/extras/android/m2repository
    steps:
      - run:
          name: Switch timezone to Moscow
          command: sudo cp /usr/share/zoneinfo/Europe/Moscow /etc/localtime
      - checkout
      - run:
          name: Accept-licenses
          command: sdkmanager --update && yes | sdkmanager --licenses
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Build assembleDebug
          command: ./gradlew assembleDebug
      - store_artifacts:
          path: TeamCode/build/outputs/apk
          destination: apk
      - run:
          name: Deploy
          command: sh ./deploy.sh $CIRCLE_BRANCH
