version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Build assembleDebug
          command: ./gradlew assembleDebug
      - store_artifacts:
          path: TeamCode/build/outputs/apk
          destination: apk
      - run:
          name: Deploy
          command: sh ./deploy.sh
