#!/bin/bash

# Originally written by Ralf Kistner <ralf@embarkmobile.com>, but placed in the public domain
# Improved by Daniele Segato

set +e

bootanim=""
starttime=$(date +%s)
failcounter=0
timeout_in_sec=360
checkpoints=(`seq 0 60 $timeout_in_sec`)

# shift
checkpoints=(${checkpoints[@]:1})

until [[ "$bootanim" =~ "stopped" ]]; do
  bootanim=`adb -e shell getprop init.svc.bootanim 2>&1 &`
  if [[ "$bootanim" =~ "device not found"
    || "$bootanim" =~ "device offline"
    || "$bootanim" =~ "running" ]]; then
    let "failcounter += 1"
    difftime=$(date +%s)
    let "difftime -= starttime"
    echo "Waiting for emulator to start: boot logo is - $bootanim - ($failcounter checks, $difftime / $timeout_in_sec sec)"
    if [[ $difftime -gt timeout_in_sec ]]; then
      echo "Timeout ($timeout_in_sec seconds) reached; failed to start emulator"
      echo "### Emulator properties:"
      adb -e shell getprop
      echo "### Emulator logcat:"
      adb -e logcat -d
      echo "### Emulator dmesg:"
      adb -e shell dmesg
      echo "Killing emulator..."
      adb -e emu kill
      exit 1
    elif [[ $difftime -gt checkpoints ]]; then
      # optionally print something more about whats going on every minute (add here)
      #echo "Checkpoint after ($difftime seconds):"
      # shift to next checkpoint
      checkpoints=(${checkpoints[@]:1})
    fi
  fi
  sleep 1
done

echo "Emulator is ready"

set -e
